### ISSUE TITLE
Feature Request: Read Protection

### ISSUE THREAD

**Issue by gicking** [ch32-rs/wlink#14]
Hello,

is it possible to enable and disable the CH32Vxx flash read-out protection (see image below)? I understand that - at least for CH32V003 - protection is enabled by default, so I assume this must be possible somehow...?

![grafik](https://github.com/ch32-rs/wlink/assets/10261226/23ccb1d3-3d2d-40a9-81f6-2c1164601e5e)

For your advice thanks a lot in advance!

Greetings from Germany, Georg

**Comment by andelf** [comment]
It requires some reverse engineering. I'll check this.

**Comment by septs** [comment]
OpenOCD source code: https://github.com/xu7wong/openocd_wchlink

from https://www.wch.cn/bbs/thread-91946-1.html

archive: [openocd-wchlink.bundle.zip](https://github.com/ch32-rs/wlink/files/11699165/openocd-wchlink.bundle.zip)

**Comment by andelf** [comment]
@gicking @septs 
After digging into the WCH-LinkUtility UI, Flash protect/unprotect is only supported by CH32V003/V103/V20x/V30x/X035.

This is implemented in the newest main branch. You can check if it works.

I haven't got a CH32X035. 😢 So CH32X035 is not supported yet.

**Comment by gicking** [comment]
hi,

sorry for the long delay! I bricked my CH32V003 and had to wait for a replacement chip. 

I just tried protect/unprotect on the (new) CH32V003 and I can confirm that it works in my setup (Linux Ubuntu 22.04 with WCH-LINKE-R0-1v3. Thanks a lot!

Currently I have no other device to test it with, so should I close this issue...?

**Comment by andelf** [comment]
@gicking Thanks for I'll close this. I tested this on my CH32V003-EVT.

**Comment by smaharj1** [comment]
@andelf is CH32X035 supported yet? I tried to unprotect for X035, and it did not do anything.

**Comment by andelf** [comment]
@smaharj1  unprotect & protect changes since old version of wlink.
So I spent some time digging into the new version.
