### ISSUE TITLE
Is there a way to unlock the flash of the different boards.

### ISSUE THREAD

**Issue by KurtE** [ch32-rs/wlink#15]
That is some of the example boards I have received have their flash locked.  I needed to use the WCH Link utility
![image](https://github.com/ch32-rs/wlink/assets/1558080/d46eb07e-e74d-4a43-b9b6-3ce86ca9aa07)
unlock button to allow me to program the boards.

But after I update the USB driver to work with wlink, that become more problematic... So wondering if there is a command line way to do this.

Thanks
Kurt

**Comment by andelf** [comment]
I unlock the flash using https://github.com/ch32-rs/wchisp
It has a predefined config register map.

**Comment by KurtE** [comment]
Thanks, I will have to try it out. 

Looks like all of the artifacts up there have expired.  So will see what it takes to try to build it.
