### ISSUE TITLE
some more protocol decoding

### ISSUE THREAD

**Issue by usbman01** [ch32-rs/wlink#20]
I am working on ARM version of wch-link. It seems when using the WCH-Link utility the same protocol is used
So here is the 0x0c cmd. Maybe this can help on the RISC part too.

request:
 0x81    0x0C   0x02   Target CPU   speed

response:
  0x82     0x0C     0x01  OK

Target CPU 0x04 = F103
                   0x08 = F203

Speed 1..3 means slow medium fast
Speed 0 maybe default? 
OK response = 0x01

**Comment by andelf** [comment]
Many thanks:
I'll add the docs.

https://github.com/ch32-rs/wlink/blob/085b39b8015c5cbbda8cfe197478ab3217e1666d/src/operations.rs#L32-L36

**Comment by andelf** [comment]
I need a better scheme to document the protocol. @septs Any ideas?

**Comment by andelf** [comment]
close as completed
