### ISSUE TITLE
Set default chip type via configuration file?

### ISSUE THREAD

**Issue by gerryqd** [ch32-rs/wlink#25]
I tried to launch command without "--chip" parameter, it reports below warnings,
```
06:29:32 [INFO] WCH-Link v2.10 (WCH-LinkE-CH32V305)
06:29:32 [WARN] No expected chip type specified, assume CH32V30X (use --chip to specify chip type)
06:29:32 [INFO] Attached chip: CH32V003(0x00310500)
```

Is there any way to check the default chip number instead of always adding it to the command line?

Maybe a configuration file helpful for this? for example, a '.wlink.cfg', which has some configuration items.

**Comment by andelf** [comment]
Thanks. This can be acquired via the protocol.
