### ISSUE TITLE
[feature request] download each block respectively when hex is not sequential

### ISSUE THREAD

**Issue by kaidegit** [ch32-rs/wlink#40]
When a firmware is merged from bootloader and app, the hex file will be not sequential. However, using `wlink flash` seems to download the empty part in the middle, which would cause the download time be longer.

**Comment by andelf** [comment]
Good point. This is very useful for customized second-stage apps.

**Comment by OpusElectronics** [comment]
I was going to ask, and found this ticket. :)
The request would be when using elf files as well.

Apart from the typical bootloader/app situation, another use case is putting constant data into the non-zero-wait Flash area, something I'm trying right now.
