### ISSUE TITLE
macOS x86 is nightly build is really Arm ..

### ISSUE THREAD

**Issue by Paulo-Ferreira-ISEP** [ch32-rs/wlink#63]
On my intel Mac with Ventura, : 
`./wlink: Bad CPU type in executable`
`file wlink-macos-x64/wlink `
`wlink-macos-x64/wlink: Mach-O 64-bit arm64 executable,flags: NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>`

and many thanks for wlink!

**Comment by andelf** [comment]
Oops, it seems Github has changed its macos-latest runner to arm64. 🤣 Thanks for the report.

**Comment by andelf** [comment]
Fixed by f7a42dd12a50ed818a7e068bb9677acc8926003f
